from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle
from pypdf import PdfReader, PdfWriter

target=Path('output/pdf/documentation_refined/Project_Setup_and_Operation_Guide.pdf');tmp=Path('tmp/pdfs/technical-reference');tmp.mkdir(parents=True,exist_ok=True);page=tmp/'technical_reference.pdf'
s=getSampleStyleSheet();s.add(ParagraphStyle(name='T',parent=s['Title'],fontName='Helvetica-Bold',fontSize=22,leading=27,textColor=colors.HexColor('#102b57'),spaceAfter=9));s.add(ParagraphStyle(name='H',parent=s['Heading1'],fontName='Helvetica-Bold',fontSize=15,leading=19,textColor=colors.HexColor('#2164d5'),spaceBefore=9,spaceAfter=5));s.add(ParagraphStyle(name='B',parent=s['BodyText'],fontSize=9.3,leading=13,textColor=colors.HexColor('#263a57'),spaceAfter=6));s.add(ParagraphStyle(name='C',parent=s['BodyText'],fontSize=9.3,leading=13,textColor=colors.HexColor('#123c7a'),backColor=colors.HexColor('#edf4ff'),borderColor=colors.HexColor('#bcd2ff'),borderWidth=.5,borderPadding=8,spaceAfter=9))
def p(x,k='B'):return Paragraph(x,s[k])
def h(x):return Paragraph(x,s['H'])
def table(rows,w):
 t=Table(rows,colWidths=w,repeatRows=1);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#193d78')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),('FONTSIZE',(0,0),(-1,-1),8.2),('LEADING',(0,0),(-1,-1),10.5),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#d7e2f0')),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#f7faff')]),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]));return t
story=[p('Technical Reference: Stack and Core Files','T'),p('<b>Purpose:</b> This page identifies the technology used to build ANT-EV and the active files that make its charging-allocation logic work.','C'),h('1. Technology stack'),table([[p('<b>Technology</b>'),p('<b>Use in ANT-EV</b>')],[p('React + TypeScript'),p('Builds the interactive web interface and keeps the station data and allocation logic strongly typed.')],[p('Vite'),p('Provides the local development server and production build process.')],[p('Tailwind CSS + custom CSS'),p('Creates the interface layout, responsive screens, live allocation bars, and animations.')],[p('Lucide React'),p('Provides interface icons.')],[p('Custom TypeScript engine'),p('Runs PRISM-ANT, safety checks, simulation steps, and M1-M6 prototype inference locally in the browser.')],[p('Python + CSV datasets'),p('Supports optional dataset preparation and model-training scripts.')],[p('ReportLab / PDF tools'),p('Creates the project documentation PDFs.')],[p('npm / Node.js'),p('Installs packages and runs the application.')]], [55*mm,130*mm]),h('2. Deployment status'),p('The current project is a local browser-based demonstration. It has no backend database or cloud API. Station scenarios, model estimators, PRISM-ANT allocation, and explanations run on the local machine.'),h('3. Core software files'),table([[p('<b>File</b>'),p('<b>Role</b>')],[p('src/services/engine/stationAllocator.ts'),p('<b>The core PRISM-ANT allocator.</b> Applies safe caps, calculates readiness reserve, and shares remaining station power.')],[p('src/services/engine/prismAntEngine.ts'),p('Evaluates charging actions and hard physical/grid constraints before allocation.')],[p('src/services/models/deepLearningLayer.ts'),p('Creates M1-M6 prototype signals: energy, demand, health, thermal, future state, and strategy value.')],[p('src/App.tsx'),p('Runs each simulation step: gets decisions, calls allocation, updates SOC/temperature, and marks completed EVs.')],[p('src/components/FocusedWorkspace.tsx'),p('Shows the charge split, reasons, models, emergency view, architecture, help, and PRISM-ANT patent specification.')],[p('src/services/simulation/simulationScenarios.ts'),p('Contains the 10-EV and emergency demonstration data.')],[p('src/types/antev.ts'),p('Defines EV, station, grid, model-result, and allocation data structures.')]], [72*mm,113*mm]),h('4. Simple software flow'),p('Simulation scenario -> M1-M6 signals -> PRISM safety checks -> PRISM-ANT safe cap -> readiness reserve -> fair remaining-power share -> SOC/temperature update -> clear reason shown in the interface.')]
SimpleDocTemplate(str(page),pagesize=A4,leftMargin=18*mm,rightMargin=18*mm,topMargin=18*mm,bottomMargin=18*mm).build(story)
r=PdfReader(str(target));a=PdfReader(str(page));w=PdfWriter()
for x in r.pages:w.add_page(x)
for x in a.pages:w.add_page(x)
with open(target,'wb') as f:w.write(f)
