import React from 'react';
import { AlertTriangle, ArrowRight, BatteryCharging, CheckCircle2, Clock3, Cpu, Gauge, ShieldCheck, Sun, Zap } from 'lucide-react';
import type { ChargingStation, EVDigitalTwin, FleetTwinState, GridTwinState, PrismAntDecisionResult } from '../../types/antev';
interface Props { evs:EVDigitalTwin[]; stations:ChargingStation[]; grid:GridTwinState; fleet:FleetTwinState; decisions:Record<string,PrismAntDecisionResult>; onSelectEv:(ev:EVDigitalTwin)=>void; onTriggerNegotiation:(id:string)=>void; onNavigateTab:(tab:string)=>void; }
const actionLabel: Record<string,string> = { CHARGE_NOW_FAST:'Charge now', CHARGE_NOW_STANDARD:'Charge now', COOPERATIVE_DELAY:'Wait', REDUCE_POWER:'Reduce power', REDIRECT_STATION:'Suggest partner station', ENERGY_RESERVATION:'Reserve energy window', ELIGIBLE_V2G_EXPORT:'Support grid', NO_CHARGE_NEEDED:'No charge needed' };
export const CommandCenter: React.FC<Props> = ({evs, stations, grid, decisions, onSelectEv, onTriggerNegotiation, onNavigateTab}) => {
 const station = stations[0]; if (!station) return null; const powered = evs.filter(ev => (decisions[ev.id]?.assignedPowerKw ?? 0) > 0); const waiting = evs.filter(ev => (decisions[ev.id]?.assignedPowerKw ?? 0) <= 0); const load = powered.reduce((sum, ev) => sum + Math.max(0, decisions[ev.id]?.assignedPowerKw ?? 0), 0); const headroom = Math.max(0, station.maxGridPowerCapacityKw-load); const urgent = [...evs].sort((a,b) => (decisions[b.id]?.candidateActions.find(x => x.action === decisions[b.id]?.selectedAction)?.prismAntScore ?? 0) - (decisions[a.id]?.candidateActions.find(x => x.action === decisions[a.id]?.selectedAction)?.prismAntScore ?? 0)); const action = urgent[0] && decisions[urgent[0].id]; const gridText = grid.gridStatus === 'OPTIMAL' ? 'Normal' : grid.gridStatus.replace('_',' ').toLowerCase();
 return <div className="page-stack command-center"><section className="hero-panel"><div><p className="eyebrow"><span className="live-dot"/> LIVE STATION</p><h1>{station.name}</h1><p className="hero-copy">One view of what is happening at the station, what ANT–EV recommends, and why it is safe.</p></div><div className="hero-status"><span>Station health</span><strong><CheckCircle2 size={18}/> Ready to operate</strong><small>{station.availableChargers} of {station.totalChargers} chargers available · {station.location}</small></div></section>
 <section className="metric-grid"><Metric icon={<Zap/>} label="Station power" value={`${load.toFixed(0)} kW`} detail={`of ${station.maxGridPowerCapacityKw} kW site limit`} progress={load/station.maxGridPowerCapacityKw}/><Metric icon={<BatteryCharging/>} label="Charging now" value={`${powered.length}`} detail={`${Math.max(0,station.totalChargers-powered.length)} chargers open`}/><Metric icon={<Clock3/>} label="Waiting" value={`${waiting.length}`} detail="Ordered by station priority" tone="amber"/><Metric icon={<Gauge/>} label="Available headroom" value={`${headroom.toFixed(0)} kW`} detail={`Grid condition: ${gridText}`} tone={headroom < 40 ? 'amber' : 'green'}/><Metric icon={<Sun/>} label="Solar now" value={`${station.renewableSolarPowerKw} kW`} detail={`${grid.renewableAvailabilityPercent}% renewable availability`} tone="green"/></section>
 <section className="decision-layout"><article className="decision-card"><div className="section-label"><span><Cpu size={16}/> CURRENT STATION DECISION</span><button onClick={() => onNavigateTab('explainability')}>Full explanation <ArrowRight size={14}/></button></div>{action && urgent[0] ? <><div className="decision-action"><span className="action-orb"><Zap size={24}/></span><div><p>{actionLabel[action.selectedAction] ?? action.selectedAction}</p><h2>{urgent[0].name}</h2><small>{action.assignedPowerKw > 0 ? `${action.assignedPowerKw} kW allocated` : 'No power allocation now'} · target {action.targetSocPercent}%</small></div></div><div className="reason-box"><b>Why this decision</b><p>{action.explainability.winningFactorSummary}</p></div><div className="safety-row"><ShieldCheck size={18}/><span><b>Safety Guard passed</b> — the chosen action is checked against charger, site, battery, and departure limits.</span></div></> : <p>No session decision is available for this scenario.</p>}</article>
 <article className="station-map"><div className="section-label"><span>CHARGER STATUS</span><button onClick={() => onNavigateTab('live-station')}>Open station <ArrowRight size={14}/></button></div><div className="bay-grid">{Array.from({length: station.totalChargers},(_,i) => {const ev=powered[i]; return <button key={i} onClick={() => ev && onSelectEv(ev)} className={ev ? 'bay occupied' : 'bay'}><span>Bay {String(i+1).padStart(2,'0')}</span><b>{ev ? `${(decisions[ev.id]?.assignedPowerKw ?? 0).toFixed(0)} kW` : 'Available'}</b><small>{ev ? `${ev.telemetry.soc}% → ${decisions[ev.id]?.targetSocPercent}%` : 'Ready for next session'}</small></button>})}</div></article></section>
 <section className="content-grid"><article className="surface"><div className="section-label"><span>PRIORITY QUEUE</span><button onClick={() => onNavigateTab('charging-queue')}>View all <ArrowRight size={14}/></button></div><div className="priority-list">{urgent.slice(0,5).map((ev,index) => { const dec=decisions[ev.id]; return <button key={ev.id} onClick={() => {onSelectEv(ev);onTriggerNegotiation(ev.id)}}><span className="queue-number">{index+1}</span><span className="session-name"><b>{ev.name}</b><small>{ev.telemetry.soc}% SOC · departure in {ev.mobility.departureDeadlineMin} min</small></span><span className="decision-chip">{dec ? actionLabel[dec.selectedAction] : 'Review'}</span></button>})}</div></article><article className="surface"><div className="section-label"><span><AlertTriangle size={15}/> LOOKING AHEAD</span></div><h3>{station.forecastDemand30m} kW expected in 30 min</h3><p className="muted">Demand forecast comes from the active demo scenario. ANT–EV keeps {headroom.toFixed(0)} kW available while evaluating urgent arrivals and flexible sessions.</p><div className="forecast-bars"><i style={{height:`${Math.min(100,station.forecastDemand15m/station.maxGridPowerCapacityKw*100)}%`}}/><i style={{height:`${Math.min(100,station.forecastDemand30m/station.maxGridPowerCapacityKw*100)}%`}}/><i style={{height:`${Math.min(100,station.forecastDemand60m/station.maxGridPowerCapacityKw*100)}%`}}/></div><small className="bar-labels">15 min <span>30 min</span><span>60 min</span></small></article></section></div>;
};
function Metric({icon,label,value,detail,progress,tone='' }:{icon:React.ReactNode;label:string;value:string;detail:string;progress?:number;tone?:string}) { return <article className={`metric-card ${tone}`}><span className="metric-icon">{icon}</span><p>{label}</p><h2>{value}</h2><small>{detail}</small>{progress !== undefined && <div className="progress"><i style={{width:`${Math.min(100,progress*100)}%`}}/></div>}</article> }
